source 'https://rubygems.org'

gem "github-pages", group: :jekyll_plugins
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'kramdown', '>= 2.3.0'

group :jekyll_plugins do
    gem 'jekyll-paginate'
    gem 'jekyll-sitemap'
  end